language: node_js
node_js:
  - "6"
cache:
  directories:
    - "node_modules"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.6.0
  - export PATH="$HOME/.yarn/bin:$PATH"
before_script:
  - yarn install
script:
  - yarn test
after_success:
  - yarn test:coverage:report
